In [1]:
import numpy as np
#import scipy as sp
#import matplotlib.pyplot as plt

## Generic equations

$$ R(\theta) = \begin{bmatrix}\cos{(\theta)} & -\sin{(\theta)} \\ \sin{(\theta)} & \cos{(\theta)}\end{bmatrix} $$

$$ T(\theta, \boldsymbol{t}) = \begin{bmatrix}\cos{(\theta)} & -\sin{(\theta)} & t_x \\ \sin{(\theta)} & \cos{(\theta)} &t_y \\ 0 & 0 & 1\end{bmatrix} $$

$$ T(\theta, \boldsymbol{t})^{-1} = \begin{bmatrix} R(\theta)^T & -R(\theta)^T \pmb{t} \\ \pmb{0}^T & 1\end{bmatrix}  $$

In [2]:
# Helper functions

def createR2D(theta):
    return np.array([[np.cos(theta), -np.sin(theta)],[np.sin(theta),np.cos(theta)]])

def createT2D(theta,t):
    assert (t.shape == (2,)),"Incorrect translation size"
    T = np.eye(3)
    T[:2,:2] = createR2D(theta)
    T[:2,2] = t
    return T

def createTinv2D(T):
    assert (T.shape == (3,3)),"Incorrect size"
    Tinv = np.empty_like(T)
    np.copyto(Tinv,T)
    Tinv[:2,:2] = T[:2,:2].T
    Tinv[:2,2] = (-T[:2,:2].T).dot(T[:2,2])
    return Tinv

## Exercises

### 1 Rotation only in 2D

a) A vector is given by $\pmb{p}^a = [4, 3]^T$. Calculate $\pmb{p}^b$, given $\theta = \dfrac{\pi}{3}$.

In [3]:
R = createR2D(np.pi/3)
R.dot(np.array([4,3]))

array([-0.59807621,  4.96410162])

b) A vector is given by $\pmb{p}^b = [2,1]^T$. Calculate $\pmb{p}^a$, given ${R}^{ab} = \begin{bmatrix}\cos{(\pi/3)} & -\sin{(\pi/3)} \\ \sin{(\pi/3)} & \cos{(\pi/3)}\end{bmatrix}$.

In [4]:
R = createR2D(np.pi/3)
p_b = np.array([2,1])
R.dot(p_b)

array([0.1339746 , 2.23205081])

### 2 Rotation and translation in 2D

a) A vector is given by $\pmb{p}^a = [4, 3]^T$. Calculate $\pmb{p}^b$, given $\theta^{ab} = \dfrac{\pi}{6}$, and $t_b^a=[3, 1]^T$.

In [5]:
T_ab = createT2D(np.pi/6,np.array([3,1]))
print(createTinv2D(T_ab).dot(np.array([4,3,1])))
#check print(np.linalg.inv(T_ab).dot(np.array([4,3,1])))

[1.8660254  1.23205081 1.        ]


b) Calculate the transformation $T^{ac}$ given


$T^{ab}=\begin{bmatrix}\cos{(\pi/3)} & -\sin{(pi/3)} & 1 \\ \sin{(pi/3)} & \cos{(pi/3)} & 2 \\ 0 & 0 & 1\end{bmatrix}$ and $T^{cb}=\begin{bmatrix}\cos{(\pi/4)} & -\sin{(\pi/4)} & -2 \\ \sin{(\pi/4)} & \cos{(\pi/4)} & 3 \\ 0 & 0 & 1\end{bmatrix}$.

In [6]:
Tab = createT2D(np.pi/3,np.array([1,2]))
Tcb = createT2D(np.pi/4,np.array([-2,3]))
Tbc = createTinv2D(Tcb)

Tab.dot(Tbc)

array([[ 0.96592583, -0.25881905,  3.70830879],
       [ 0.25881905,  0.96592583, -0.38013939],
       [ 0.        ,  0.        ,  1.        ]])

c) Show that $T T^{-1} = I_3$

$$ T(\theta, \boldsymbol{t}) = \begin{bmatrix}R & \pmb{t} \\ \pmb{0}^T & 1\end{bmatrix} $$

$$ T(\theta, \boldsymbol{t})^{-1} = \begin{bmatrix} R^T & -R^T \pmb{t} \\ \pmb{0}^T & 1\end{bmatrix}$$

\begin{align}
TT^{-1} & = \begin{bmatrix}R & \pmb{t} \\ \pmb{0}^T & 1\end{bmatrix} \begin{bmatrix} R^T & -R^T \pmb{t} \\ \pmb{0}^T & 1\end{bmatrix} \\
& = \begin{bmatrix}R R^T + \pmb{t} \pmb{0}^T  & -R R^T \pmb{t} + \pmb{t} \\ \pmb{0}^T R^T + \pmb{0}^T & -\pmb{0}^T R^T \pmb{t} +1 \end{bmatrix} \\
& = \begin{bmatrix}I & 0 \\ 0 & 1\end{bmatrix}
\end{align}